[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''
ignore_missing_imports = true

[tool.black]
line-length = 120
skip-string-normalization = true


