# Generated by Django 4.1.7 on 2023-07-14 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="lockout_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
