# Generated by Django 4.1.7 on 2023-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0006_alter_loginattempt_lockout_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="last_attempt_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
