# Generated by Django 4.1.7 on 2023-07-18 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0007_alter_loginattempt_last_attempt_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="lockout_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
