# Generated by Django 4.1.7 on 2023-07-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0009_loginattempt_max_login_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="login_attempts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userservice.loginattempt",
            ),
        ),
    ]
