# Generated by Django 4.1.7 on 2023-07-20 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0010_users_login_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="login_attempts",
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
