# Generated by Django 4.1.7 on 2023-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservice", "0011_remove_users_login_attempts_loginattempt_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="last_attempt_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
