# Generated by Django 4.1.7 on 2023-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0013_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
