# Generated by Django 4.1.7 on 2023-11-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0014_alter_users_address_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
