# Generated by Django 4.1.7 on 2023-11-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0015_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
