# Generated by Django 4.1.7 on 2023-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0017_users_avatar_alter_loginattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='img/profile/avatar.png', null=True, upload_to=''),
        ),
    ]
