# Generated by Django 4.1.7 on 2023-11-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0018_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile/avatar.png', null=True, upload_to='images/profile/'),
        ),
    ]
