# Generated by Django 4.1.7 on 2024-01-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0019_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
