# Generated by Django 4.1.7 on 2024-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0020_alter_loginattempt_user_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='last_attempt_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
